//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafeMessenge.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SafeMessenge.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Users.Id AS [Id],
        ///    Users.UserName AS [Name],
        ///    Users.Password AS [Password],
        ///    Users.IsAdmin AS [IsAdmin],
        ///    PaswordTypes.Id AS [PasswordTypeId],
        ///    PaswordTypes.Name AS [PasswordTypeName],
        ///    PaswordTypes.ValidationRegex AS [PasswordValidationRegex],
        ///    PaswordTypes.Description AS [PasswordTypeDescription]
        ///FROM Users
        ///LEFT JOIN PaswordTypes ON PaswordTypes.Id = PasswordTypeId.
        /// </summary>
        internal static string GetAllUsers {
            get {
                return ResourceManager.GetString("GetAllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Id, Name, ValidationRegex, Description FROM PaswordTypes.
        /// </summary>
        internal static string GetPasswordTypes {
            get {
                return ResourceManager.GetString("GetPasswordTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Users.Id AS [Id],
        ///    Users.UserName AS [Name],
        ///    Users.Password AS [Password],
        ///    Users.IsAdmin AS [IsAdmin],
        ///    PaswordTypes.Id AS [PasswordTypeId],
        ///    PaswordTypes.Name AS [PasswordTypeName],
        ///    PaswordTypes.ValidationRegex AS [PasswordValidationRegex],
        ///    PaswordTypes.Description AS [PasswordTypeDescription]
        ///FROM Users
        ///LEFT JOIN PaswordTypes ON PaswordTypes.Id = PasswordTypeId
        ///WHERE Users.Id = @Id;.
        /// </summary>
        internal static string GetUserById {
            get {
                return ResourceManager.GetString("GetUserById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TABLE IF EXISTS [PaswordTypes];
        ///CREATE TABLE IF NOT EXISTS [PaswordTypes] (
        ///  [Id] INTEGER PRIMARY KEY AUTOINCREMENT
        ///, [Name] NVARCHAR(64) NOT NULL
        ///, [ValidationRegex] TEXT NOT NULL
        ///, [Description] TEXT NOT NULL
        ///, [Created] DATETIME default current_timestamp
        ///);
        ///INSERT OR IGNORE INTO PaswordTypes ([Name], [ValidationRegex], [Description]) VALUES
        ///(&apos;Простий&apos;, &apos;.&apos;, &apos;Пароль повивнен містити мінімум один символ&apos;),
        ///(&apos;Складний&apos;, &apos;^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d]{8,}$&apos;, &apos;Пароль має містити мі [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InsertTables {
            get {
                return ResourceManager.GetString("InsertTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Users ([UserName], [Password], [PasswordTypeId], [IsAdmin]) VALUES
        ///(@Name, &apos;&apos;, @PasswordTypeId, @IsAdmin).
        /// </summary>
        internal static string InsertUser {
            get {
                return ResourceManager.GetString("InsertUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [Users] SET
        ///[Password] = @Password,
        ///[IsAdmin] = @IsAdmin,
        ///[PasswordTypeId] = @PasswordTypeId
        ///WHERE [Id] = @Id;
        ///.
        /// </summary>
        internal static string UpdateUser {
            get {
                return ResourceManager.GetString("UpdateUser", resourceCulture);
            }
        }
    }
}
